/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceld;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eder
 */
public class Criar extends javax.swing.JFrame {

    /**
     * Creates new form Criar
     */
    public Criar() {
        initComponents();
    }
    
    String url = "jdbc:oracle:thin:@localhost:1521:xe";
			String email;
                        
                        String nome;
                        String senha;
                        String data_nascimento;
                        String area;	
			String sql_inserir = "insert into dadosUser values(?,?,?,?,?)";
                        public void create()throws Exception {
                            int contador=0;
                            try(Connection con = DriverManager.getConnection(url, "ldev", "ld");
                            PreparedStatement stm = con.prepareStatement(sql_inserir)){
                        
                            
                            
                            
                            String sql_checar = "select email from dadosUser";
                            try(PreparedStatement stm2 = con.prepareStatement(sql_checar);
                            ResultSet rs2 = stm2.executeQuery()){
                            while(rs2.next()){
                                if(rs2.getString("email").equals(this.email)){
                                    contador +=1;                                  
                                    break;
                                }
                                
                                
                        }if(contador==0){
                            stm.setString(1, email);
                            stm.setString(2, nome);
                            stm.setString(3, senha);
                            stm.setString(4, data_nascimento);
                            stm.setString(5, area);
                            stm.addBatch();
                            stm.executeBatch();
                            JOptionPane.showMessageDialog(null, "usuario Criado");
                            this.dispose();
                        }else if(contador>0){
                        JOptionPane.showMessageDialog(null, "Email Ja cadastrado, Tente outro");
                        
                        }
                    }
    
   }
                        }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CriarNome = new javax.swing.JTextField();
        CriarEmail = new javax.swing.JTextField();
        CriarNascimento = new javax.swing.JTextField();
        CriarArea = new javax.swing.JTextField();
        CriarConta = new javax.swing.JButton();
        CriarSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 338));
        setPreferredSize(new java.awt.Dimension(400, 375));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Digite Seu Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Digite seu email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 120, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data de nascimento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 140, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Digite sua Senha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Informe sua area");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 230, 119, 17);

        CriarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CriarNome);
        CriarNome.setBounds(150, 30, 200, 30);

        CriarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CriarEmail);
        CriarEmail.setBounds(150, 130, 200, 30);

        CriarNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(CriarNascimento);
        CriarNascimento.setBounds(150, 180, 200, 30);

        CriarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarAreaActionPerformed(evt);
            }
        });
        getContentPane().add(CriarArea);
        CriarArea.setBounds(150, 230, 200, 30);

        CriarConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CriarConta.setText("Criar Conta");
        CriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(CriarConta);
        CriarConta.setBounds(120, 270, 150, 50);
        getContentPane().add(CriarSenha);
        CriarSenha.setBounds(150, 80, 200, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgroundCriar.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarEmailActionPerformed

    private void CriarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarNomeActionPerformed

    private void CriarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarAreaActionPerformed

    private void CriarNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarNascimentoActionPerformed

    private void CriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarContaActionPerformed
        try {
            // TODO add your handling code here:
            
           
            email = CriarEmail.getText();
            area = CriarArea.getText();
            data_nascimento = CriarNascimento.getText();
           
            
            
            
            nome = CriarNome.getText();
            senha = new String(CriarSenha.getPassword());
            this.create();
            
        } catch (Exception ex) {
            Logger.getLogger(Criar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_CriarContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Criar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Criar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CriarArea;
    private javax.swing.JButton CriarConta;
    private javax.swing.JTextField CriarEmail;
    private javax.swing.JTextField CriarNascimento;
    private javax.swing.JTextField CriarNome;
    private javax.swing.JPasswordField CriarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
