/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceld;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Eder
 */
public class entrar extends javax.swing.JFrame {

    /**
     * Creates new form entrar
     */
    public entrar() {
        initComponents();
    }
    Criar Criarconta = new Criar();
    BemVindo mensagemBV = new BemVindo();
    

    
    String url ="jdbc:oracle:thin:@localhost:1521:xe";
    String sql;
    String email;
    String senha;

	public boolean logar()throws Exception{
            boolean logado = false;
            sql = "select senha from dadosUser where email=('"+email+"')";
            try(Connection con2 = DriverManager.getConnection(url, "ldev", "ld");
            PreparedStatement stm2 = con2.prepareStatement(sql);
            ResultSet rs2 = stm2.executeQuery()){
            while(rs2.next()){
                if(rs2.getString("senha").equals(senha)){
                    logado = true;
                    break;
                }else{
                    logado = false;
                    break;
                }
            }
            }                               		
        return logado;
    }
    
    
    
    /**;
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caixaEmail = new javax.swing.JFormattedTextField();
        caixaSenha = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(605, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 71, 34);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 80, 34);

        caixaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaEmailActionPerformed(evt);
            }
        });
        getContentPane().add(caixaEmail);
        caixaEmail.setBounds(20, 50, 230, 30);

        caixaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(caixaSenha);
        caixaSenha.setBounds(20, 130, 230, 30);

        entrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entrar.setText("Logar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(90, 210, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Criar Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 260, 140, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 299);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caixaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaEmailActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
            
            email = caixaEmail.getText();
            senha = new String(caixaSenha.getPassword());
            boolean logando = false;
            
       
        try {
            logando = this.logar();
        } catch (Exception ex) {
            Logger.getLogger(entrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            if(logando==true){
                try {
                    mensagemBV = new BemVindo();
                } catch (Exception ex) {
                    Logger.getLogger(entrar.class.getName()).log(Level.SEVERE, null, ex);
                }
                mensagemBV.setLocationRelativeTo(null);
                mensagemBV.setVisible(true);
                mensagemBV.setResizable(true);
                                       
                
                try {
                    mensagemBV.bemVindo(email);
                } catch (Exception ex) {
                    Logger.getLogger(entrar.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
                
                
     }else{
            JOptionPane.showMessageDialog(null, "Email ou Senha incorreta");
            }
            
               
    }//GEN-LAST:event_entrarActionPerformed

    private void caixaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //fazer aparecer a tela
        
        Criarconta = new Criar();
        Criarconta.setLocationRelativeTo(null);
        Criarconta.setVisible(true);
        Criarconta.setResizable(true);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entrar().setVisible(true);
            }
                
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField caixaEmail;
    private javax.swing.JPasswordField caixaSenha;
    private javax.swing.JButton entrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
